# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AeroDataVisualizer
                                 A QGIS plugin
 This plugin allows to visualize aeronautical data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-08
        copyright            : (C) 2024 by BEA
        email                : louise.redlinger@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AeroDataVisualizer class from file AeroDataVisualizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aero_data_visualizer import AeroDataVisualizer
    return AeroDataVisualizer(iface)
